---
title: "A novel role for alkyladenine DNA glycosylase in regulating alkylation-induced ER stress"
subtitle: "Figure S1, Panel A"
author: "L Milano, CF Charlier, R Andreguetti, T Cox, E Healing, MP Thomé, RM Elliott, JY Masson, LD Samson, JY Masson, G Lenz, JAP Henriques, A Nohturfft and LB Meira"
output:
  html_notebook:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 3
    code_folding: "hide"
    number_sections: FALSE
    theme: "readable"
    highlight: "tango"
    fig_caption: TRUE
    css: "./source/styles.css"
---

```{js}
function myFunction(id) {
  var x = document.getElementById(id);
  if (x.style.display === 'none') {
    x.style.display = 'block';
  } else {
    x.style.display = 'none';
  }
}
```

<div class='comments'>
Note: This analysis requires input data generated by an earlier script.
</div>

## Objective  
<div class='comments'>
Generate boxplot of normalized expression data.
</div>


## Setup  

* Clear memory and console  
* Load packages  
* Get current script name  

```{r CLEAR MEMORY AND PACKAGES AND CONSOLE, results="hide"}
# Clear memory
rm(list=setdiff(ls(all=TRUE), c(".Random.seed")))
# Clear console
cat("\014")
```

## Set up  
```{r Packages, include=FALSE, results="hide"}
library(dplyr)
library(magrittr)
```


```{r Get script name,  class.output="txt_output"}
this.script <- rstudioapi::getActiveDocumentContext()$path %>% basename
cat("Script:", this.script)
```

## Load data  
```{r}
data.file <- "data/01_Raw_Data_Processing.Rmd.eset.RDS"
stopifnot(file.exists(data.file))
eset <- readRDS(data.file)
cat("File read:", data.file)
rm(data.file)
```


## Boxplot of log2 transformed data
```{r BOXPLOT ESET, message=FALSE, warning=FALSE, fig.height=4}
op <- par()
colorz <- rep(RColorBrewer::brewer.pal(4, name="Paired"), each=3)
par(mar=c(7,4,2,2)) # default is (5,4,4,2)
eset %>% Biobase::exprs(.) %>% log2(.) %>%
  boxplot(., las=2, col=colorz, main="Figure S1A")
par(op)
rm(op, colorz)
```

## Save plot  

```{r SAVE PLOT}
op <- par()
colorz <- rep(RColorBrewer::brewer.pal(4, name="Paired"), each=3)
par(mar=c(7,4,2,2)) # default is (5,4,4,2)

out.file <- "Figure_S1_A.pdf"
pdf(file=out.file, paper="a4")

eset %>% Biobase::exprs(.) %>% log2(.) %>%
  boxplot(., las=2, col=colorz, main="Figure S1A")

dev.off()

par(op)
rm(op, colorz)
```



### Session info  

<button class="button" onclick="myFunction('DIV_1')">Show/hide session info</button>
<div id="DIV_1" class="div_default_hide">

```{r SESSION INFO DATE, results="asis"}
cat("Date:", format(Sys.time(), "%a %d-%b-%Y %H:%M:%S"), "<br>\n")
```

```{r print_session_info, R.options=list(width=70)}
devtools::session_info()
```
</div>
  
```{js}
var divsToHide = document.getElementsByClassName("div_default_hide");
for(var i = 0; i < divsToHide.length; i++)
{
  divsToHide[i].style.display = 'none';
}
```



